[package]
name = "noabspath"
version = "0.1.0"
authors = ["William Droz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
glob = "~0.3.0"
rayon = "~1.3.1"
regex = "~1.3.9"
colored = "~1.9"
